### ISSUE TITLE
How to create a dataset？

### ISSUE THREAD

**Issue by GuichenSociety** [jyopari/VINN#3]
Hello, how to make the labels. json in the dataset? Is it processed using OpenSfM library in the paper

**Comment by notmahi** [comment]
Hi, if you are interested in starting on a VINN or VINN-like project, it may be better to start with the [Dobb-E](https://dobb-e.com) infrastructure, documented here: https://docs.dobb-e.com/ . We shifted to using an iPhone to collect the data since extracting the actions/labels are much simpler.

**Comment by GuichenSociety** [comment]
Thank you very much for your answer

**Comment by GuichenSociety** [comment]
Thank you very much for your answer
